services:
  db:
    image: postgres
    container_name: "naruto_db"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d naruto -U n4ruto"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: on-failure
  app:
    image: naruto-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "naruto_api"
    ports:
      - "5000:3100"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    # develop:
    #   watch:
    #     - path: ./src
    #       action: sync
    #       target: /usr/local/app/src
    #       ignore:
    #         - node_modules/
    #     - path: ./src/package.json
    #       action: rebuild

volumes:
  pgdata:
