services:
  app:
    image: naruto-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'naruto_api'
    ports:
      - '5000:4000'
    depends_on:
      - db
    volumes:
      - .:/app
    develop:
      watch:
        - path: ./app/src
          action: sync
          target: ./app/src
          ignore:
            - node_modules/
        - path: ./app/package.json
          action: rebuild

  db:
    image: postgres
    container_name: 'naruto_db'
    ports:
      - '5432:5432'
    # environment:
    #   POSTGRES_USER: ${DB_USER}
    #   POSTGRES_PASSWORD: ${DB_PASS}
    #   POSTGRES_DB: ${DB_NAME}
    env_file:
      - path: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
